/**
 * shared/glossary.js
 *
 * Dependency-free hover/click/focus tooltip glossary for the RL Demos site.
 * Works with mouse, touch, and keyboard: terms are rendered as a <button>
 * (focusable, tabindex-native) that toggles a tooltip on click or Enter/Space,
 * and dismisses on Escape or an outside click/tap. ARIA attributes describe
 * the relationship for screen readers.
 *
 * Exposed API:
 *   glossary                -> the mutable term -> definition map (Object)
 *   addTerms(newTerms)      -> merges newTerms into the shared glossary map
 *   glossaryTerm(term, displayText) -> string (HTML markup for a glossary span)
 *   initGlossary(root)      -> void (wires up event listeners once per page;
 *                                    root defaults to document)
 *
 * Usage on a demo page:
 *   import { glossaryTerm, addTerms, initGlossary } from '../shared/glossary.js';
 *   addTerms({ 'reward shaping': 'Modifying rewards to speed up learning.' });
 *   container.innerHTML = `Uses ${glossaryTerm('replay buffer')} to store...`;
 *   initGlossary(); // call once, after the markup above is in the DOM
 */

// ---------------------------------------------------------------------------
// Starter glossary — plain-English, short definitions. Extend via addTerms().
// ---------------------------------------------------------------------------

export const glossary = {
  "MDP":
    "Markov Decision Process: the math framework for RL — states, actions, rewards, and transition probabilities, where the next state depends only on the current state and action (not the full history).",
  "state space":
    "The set of all possible situations the agent can observe or be in.",
  "action space":
    "The set of all possible actions the agent can choose from in a given state.",
  "reward function":
    "The rule that scores how good or bad an outcome was, telling the agent what to optimize for.",
  "policy":
    "The agent's strategy: a mapping from states to actions (or to a probability distribution over actions).",
  "value function":
    "A prediction of how much total future reward an agent can expect from a given state (or state-action pair) if it keeps acting under its current policy.",
  "Q-value":
    "The expected total future reward of taking a specific action in a specific state, then continuing to act under the policy afterward.",
  "discount factor":
    "A number between 0 and 1 (often written gamma) that shrinks the value of future rewards compared to immediate ones, so the agent doesn't weight distant rewards as heavily as near-term ones.",
  "replay buffer":
    "A memory bank of past (state, action, reward, next state) transitions that the agent samples from to learn, instead of learning only from the most recent experience.",
  "target network":
    "A slow-moving, periodically-updated copy of the main network used to compute stable learning targets, which prevents the moving-target instability of updating a network against its own live predictions.",
  "on-policy":
    "A learning method that can only learn from data generated by its current policy — once the policy changes, old data must be discarded.",
  "off-policy":
    "A learning method that can learn from data generated by any policy, including old experience or another agent's actions, not just the current policy.",
  "trajectory":
    "A recorded sequence of states, actions, and rewards the agent experienced, typically over one episode.",
  "return":
    "The total (usually discounted) sum of rewards collected from a point in time onward, used as the learning signal for how good a trajectory was.",
  "advantage":
    "How much better (or worse) a specific action was compared to the average action in that state — the return minus a baseline value estimate.",
  "baseline":
    "A reference value (often a learned value-function estimate) subtracted from the return to reduce noise in the learning signal, without changing what the optimum policy is.",
  "clipped surrogate objective":
    "PPO's training objective, which limits how much the policy is allowed to change in a single update by clipping the probability ratio between the new and old policy, keeping updates stable.",
  "epsilon-greedy":
    "An exploration strategy that picks the best-known action most of the time but picks a random action with probability epsilon, so the agent keeps discovering new behavior.",
  "sample efficiency":
    "How much reward-worthy learning an algorithm extracts per unit of experience collected — a more sample-efficient method needs fewer environment interactions to reach the same performance.",
};

// ---------------------------------------------------------------------------
// Extension API
// ---------------------------------------------------------------------------

/**
 * Merges page-specific terms into the shared glossary map without requiring
 * edits to this file. Overwrites any existing key with the same name.
 *
 * @param {Object<string,string>} newTerms - Map of term -> definition to add.
 */
export function addTerms(newTerms) {
  Object.assign(glossary, newTerms);
}

// ---------------------------------------------------------------------------
// Markup generation
// ---------------------------------------------------------------------------

let idCounter = 0;

/** Escapes text for safe interpolation into HTML attribute or text content. */
function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Builds a stable-ish unique id for a tooltip element on this page load. */
function nextId() {
  idCounter += 1;
  return `glossary-tip-${idCounter}`;
}

/**
 * Returns HTML markup for an inline glossary term: a focusable button
 * displaying `displayText` (or the term itself), plus a hidden tooltip
 * <span> with the definition, wired via ARIA attributes. Call initGlossary()
 * once after this markup is inserted into the DOM so the toggle/dismiss
 * behavior is attached.
 *
 * If the term isn't found in the glossary map, the text is still rendered,
 * but plainly (no button/tooltip), so a typo doesn't break the page.
 *
 * @param {string} term - Key to look up in the glossary map (case-insensitive).
 * @param {string} [displayText] - Text to show instead of the term itself.
 * @returns {string} HTML markup string.
 */
export function glossaryTerm(term, displayText) {
  const key = Object.keys(glossary).find(
    (candidate) => candidate.toLowerCase() === String(term).toLowerCase()
  );
  const shown = escapeHtml(displayText || term);

  if (!key) {
    return `<span class="glossary-missing">${shown}</span>`;
  }

  const definition = escapeHtml(glossary[key]);
  const tipId = nextId();

  return (
    `<span class="glossary-term-wrap">` +
    `<button type="button" class="glossary-term" data-glossary-toggle ` +
    `aria-describedby="${tipId}" aria-expanded="false">${shown}</button>` +
    `<span id="${tipId}" class="glossary-tooltip" role="tooltip" hidden>${definition}</span>` +
    `</span>`
  );
}

// ---------------------------------------------------------------------------
// Interaction wiring
// ---------------------------------------------------------------------------

const WIRED_FLAG = "__rlGlossaryWired";

/**
 * Wires up click/keyboard toggle and dismiss behavior for every glossary term
 * currently in `root` (defaults to the whole document). Safe to call more
 * than once — a page can call it again after inserting more glossary markup;
 * already-wired root/document combinations are skipped via a flag.
 *
 * Behavior:
 *  - Click or Enter/Space on a glossary-term button toggles its tooltip.
 *  - Escape closes any open tooltip and returns focus to its button.
 *  - Clicking/tapping outside an open tooltip closes it.
 *  - Only one tooltip is open at a time.
 *
 * @param {Document|Element} [root=document] - Scope to search for glossary
 *   term buttons that haven't been wired yet.
 */
export function initGlossary(root = document) {
  const buttons = root.querySelectorAll(
    "[data-glossary-toggle]:not([data-glossary-wired])"
  );

  buttons.forEach((button) => {
    button.setAttribute("data-glossary-wired", "true");
    button.addEventListener("click", (event) => {
      event.stopPropagation();
      toggleTooltip(button);
    });
  });

  if (!document[WIRED_FLAG]) {
    document[WIRED_FLAG] = true;

    document.addEventListener("keydown", (event) => {
      if (event.key === "Escape") {
        const openButton = document.querySelector(
          '[data-glossary-toggle][aria-expanded="true"]'
        );
        if (openButton) {
          closeTooltip(openButton);
          openButton.focus();
        }
      }
    });

    document.addEventListener("click", () => {
      closeAllTooltips();
    });
  }
}

function getTooltip(button) {
  const tipId = button.getAttribute("aria-describedby");
  return tipId ? document.getElementById(tipId) : null;
}

function toggleTooltip(button) {
  const isOpen = button.getAttribute("aria-expanded") === "true";
  closeAllTooltips();
  if (!isOpen) {
    openTooltip(button);
  }
}

function openTooltip(button) {
  const tooltip = getTooltip(button);
  if (!tooltip) return;
  tooltip.hidden = false;
  button.setAttribute("aria-expanded", "true");
}

function closeTooltip(button) {
  const tooltip = getTooltip(button);
  if (!tooltip) return;
  tooltip.hidden = true;
  button.setAttribute("aria-expanded", "false");
}

function closeAllTooltips() {
  document
    .querySelectorAll('[data-glossary-toggle][aria-expanded="true"]')
    .forEach((button) => closeTooltip(button));
}
